name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  backend-build:
    name: Backend Build & Test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      
      - name: Install dependencies
        working-directory: ./backend
        run: npm ci
      
      - name: Run ESLint
        working-directory: ./backend
        run: npm run lint
      
      - name: Build backend
        working-directory: ./backend
        run: npm run build
      
      - name: Run tests
        working-directory: ./backend
        run: npm test
        continue-on-error: true

  frontend-build:
    name: Frontend Build & Test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci
      
      - name: Run ESLint
        working-directory: ./frontend
        run: npm run lint
      
      - name: Type check
        working-directory: ./frontend
        run: npm run type-check
      
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build
      
      - name: Run tests
        working-directory: ./frontend
        run: npm test
        continue-on-error: true

  docker-build:
    name: Docker Build Test
    runs-on: ubuntu-latest
    needs: [backend-build, frontend-build]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false
          tags: socialmedia-backend:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Build frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: false
          tags: socialmedia-frontend:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

  notify-success:
    name: Notify Success
    runs-on: ubuntu-latest
    needs: [backend-build, frontend-build, docker-build]
    if: success()
    
    steps:
      - name: Success message
        run: |
          echo "✅ All CI checks passed\!"
          echo "Backend: Built and tested successfully"
          echo "Frontend: Built and tested successfully"
          echo "Docker: Images built successfully"
